import jsPDF from 'jspdf';

const PDFGenerator = {
  generateReport: (analysisData) => {
    if (!analysisData) return;

    // Create new PDF document
    const doc = new jsPDF();
    
    // Set up professional styling
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 15;
    const contentWidth = pageWidth - (2 * margin);
    
    // Title - increased by 200%
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(44, 62, 80); // Dark blue-gray
    const title = `Job Analysis Report: ${analysisData.jobTitle}, ${analysisData.company}`;
    doc.text(title, margin, 25);
    
    // Date and Score on same line - moved down to avoid overlap
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(128, 128, 128);
    const currentDate = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
    doc.text(`Generated on: ${currentDate}`, margin, 40);
    doc.text(`Compatibility Score: ${analysisData.score}%`, margin + 80, 40);
    
    let yPosition = 55; // Moved down significantly to avoid overlap
    
    // Section 1: Resume-Job Compatibility
    yPosition = PDFGenerator.addSection(doc, 'Resume-Job Compatibility', [
      'Skills match: 85%',
      'Experience level: Appropriate',
      'Education: Meets requirements',
      'Overall fit: Excellent'
    ], yPosition, margin);
    
    // Section 2: Gap Analysis & Transferrable Skills
    yPosition = PDFGenerator.addSection(doc, 'Gap Analysis & Transferrable Skills', [
      'Transferrable skills identified',
      'Learning opportunities highlighted',
      'Growth potential assessed',
      'Skill development plan suggested'
    ], yPosition, margin);
    
    // Section 3: Company Research
    yPosition = PDFGenerator.addSection(doc, 'Company Research', [
      'Company culture analysis',
      'Financial stability reviewed',
      'Growth trajectory assessed',
      'Employee satisfaction data'
    ], yPosition, margin);
    
    // Section 4: Recruiter Details
    yPosition = PDFGenerator.addSection(doc, 'Recruiter Details', [
      'Contact information available',
      'Application process outlined',
      'Interview preparation tips',
      'Follow-up strategy suggested'
    ], yPosition, margin);
    
    // Footer - smaller and closer to bottom
    doc.setFontSize(7);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by Automated Job Search Application', margin, doc.internal.pageSize.getHeight() - 10);
    
    // Save the PDF
    const fileName = `Job_Analysis_${analysisData.jobTitle.replace(/[^a-zA-Z0-9]/g, '_')}_${analysisData.company.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
    doc.save(fileName);
  },

  addSection: (doc, title, items, yPosition, margin) => {
    // Section title
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(44, 62, 80);
    doc.text(title, margin, yPosition);
    yPosition += 8; // Added spacing after subtitle
    
    // Section items
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(52, 73, 94);
    
    items.forEach(item => {
      doc.setFont('helvetica', 'bold');
      doc.text('•', margin, yPosition);
      doc.setFont('helvetica', 'normal');
      doc.text(item, margin + 3, yPosition);
      yPosition += 4;
    });
    
    yPosition += 8; // Added spacing after last bullet point
    return yPosition;
  }
};

export default PDFGenerator; 